### ISSUE TITLE
Any plan to support Chinese?

### ISSUE THREAD

**Issue by ryanhamilton** [timestored/qstudio#133]
user-rz

> QStudio/Pulse/SQLNotebook are amazing products! But it seems that QStudio/Pulse/SQLNotebook do not support Chinese encoding in UTF8 or GBK . Is there any plan to support it?

**Comment by ryanhamilton** [comment]
I thought we did (image below).
What isn't working? and can you outline what I would need to do?

![qstudio-utf8](https://github.com/user-attachments/assets/2c478a96-bd22-4ae0-9571-51716b19287e)

**Comment by drzwz** [comment]
Sorry for not testing it carefully. qStudio/Pulse does support UTF-8 encoded Chinese characters, but cannot directly display GBK characters, which is reasonable. So far, the only problem I have encountered is that I can input Chinese, but QStudio displays it as special characters. probably because I am using Chinese Version of Windows 11.
![qstudio](https://github.com/user-attachments/assets/49c8a6cc-025b-4ebd-91cd-72370e9835fc)

**Comment by drzwz** [comment]
Thanks. I will try to generate UTF-8 input.
1. I change Language & Region settings as following:
![qstudio1](https://github.com/user-attachments/assets/37037ceb-a20a-4b97-a548-56a58863e534)

2. I created a UTF8 file in Notepad, which can be displayed normally in Studio for kdb+(https://github.com/CharlesSkelton/studio), but not in qStudio.
![qstudio2](https://github.com/user-attachments/assets/00d53a68-4b6b-4134-b963-d15a352d5fd2)

Where did I go wrong? Thanks.

**Comment by drzwz** [comment]
qStudio:
![qstudio6](https://github.com/user-attachments/assets/62dd460b-1f13-4a1f-9b2d-bac042f090b4)
Pulse Dashboard:
![qstudio3](https://github.com/user-attachments/assets/aaffc6e3-c5da-430b-95c9-b418453fc369)
Pulse SQLEditor:
![qstudio4](https://github.com/user-attachments/assets/dbbef217-e3f7-4b3b-85bf-b53ff4687056)
Pulse SQLNotebook:
![qstudio5](https://github.com/user-attachments/assets/09c4c511-099a-45a5-a8ad-e829bec69121)

**Comment by lalz001** [comment]
The default of Code Font is ：JetBrains  Mono
![image](https://github.com/user-attachments/assets/c41190af-5ecc-4b15-b0da-b4e82a582355)
However，in this Font Chinese does not support
![image](https://github.com/user-attachments/assets/cf890d6e-81d7-4911-a5a2-d798cdc9ae2d)
BY change to other Font like ”华文宋体“，Things go to right
![image](https://github.com/user-attachments/assets/69b25d1b-4db9-4f53-ad66-5c81a347bdbb)

**Comment by ryanhamilton** [comment]
Great detective work @lalz001 not supporting chinese when first launched is too heavy a price to pay for a nice font.
I will revert the default font to monospaced in QStudio 4.03+. Anyone wanting jetbrains mono can set it themselves.

**Comment by ryanhamilton** [comment]
Should be fixed in 4.03 just released. I'll leave this issue open 2 weeks in case you want to confirm.

**Comment by drzwz** [comment]
Thank you for the fix!  The issue remains in **Pulse 3.13** (Dashboard/SQL Editor/SQLNotebook).
